### PR TITLE
doc: migrate User Story from Robot to pytest

### PR DESCRIPTION
**Pull request by tarilabs**
## Description
migrate User Story _from_ RobotFramework:

https://github.com/kubeflow/model-registry/blob/12f6cb9593c5f2381fa099053fce8e1eadc6d4db/test/robot/UserStory.robot#L72-L91

_to_ pytest,

following awesome work from @isinyaaa to introduce e2e testing directly with pytest:
- https://github.com/kubeflow/model-registry/pull/326

## How Has This Been Tested?
`make test-e2e`

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [x] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work.
- [x] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

### CODE REVIEW

**Review by isinyaaa — APPROVED** [review]
awesome Matteo!

**Comment by rareddy** [comment]
so keeping both tests?

**Comment by tarilabs** [comment]
> so keeping both tests?

for the moment yes, until we onboard every test and everyone contributing to the alternative of the robotframework as voiced.

**Review by rareddy — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
