### PR TITLE
feat: BFF is able to run (mocked) without Kubernetes

### PR DESCRIPTION
**Pull request by ederign**
In this PR:
- Kubernetes client mock
- Update on BFF readme

## Description
To make it easy for front-end and BFF developers to run FE and BFF without Kubernetes, I've created a simple mocked client that returns a model registry and points the service to localhost:8080 (where docker-compose is running).

## How Has This Been Tested?
Please go through README.md to double-check if everything works as expected. 

## Merge criteria:

- [X] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ederign** [comment]
@alexcreasy, please double-check if you can onboard with the BFF just reading the instructions?

**Comment by alexcreasy** [comment]
@ederign I've run this with `MOCK_K8S_REQUESTS=true` enabled and it works nicely, I'm able to make the requests against the API as listed in the README without any errors.

Just to note, I ran this using podman desktop with docker compose compatibility enabled, without any issues.

**Comment by ederign** [comment]
@tarilabs, we are ready to review!

**Review by tarilabs — COMMENTED** [review]
thanks https://github.com/kubeflow/model-registry/pull/190#issuecomment-2231441880
/lgtm
/approve

**Pull request merged**
