### PR TITLE
Fixes frontend lint errors

### PR DESCRIPTION
**Pull request by alexcreasy**
## Description

Fixes lint errors that prevent CI from passing in other jobs

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [ ] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

### CODE REVIEW

**Comment by alexcreasy** [comment]
@lucferbux @Griffin-Sullivan Can you take a look at this please? We have some frontend lint errors that have been checked in an are blocking other PRs from merging, this should fix them.

**Review by lucferbux — COMMENTED** [review]
/lgtm

How come this has happened? I guess there was a merge that overrode the CI

**Comment by alexcreasy** [comment]
Yeah, I'm really not sure how? I don't have permissions to merge directly, I can only approve and wait for tide to take care of it... which should mean it won't merge without a passing test job?

**Comment by lucferbux** [comment]
Not sure what have might happened, this changes come from https://github.com/kubeflow/model-registry/pull/432 I cannot check wether all those changes passed the CI now, let me take a look

**Comment by alexcreasy** [comment]
Uh oh... we now seem to have actual test failures?

**Comment by alexcreasy** [comment]
Close PR... @lucferbux will fix these in a PR that will take care of the test failures as well

**Pull request closed without merging**
