### PR TITLE
Dependency Update: bump go from 1.19 to 1.21@latest

### PR DESCRIPTION
**Pull request by tonyxrmdavidson**
This commit will update go from go1.19 to go1.21@latest

### CODE REVIEW

**Review by tarilabs — COMMENTED** [review]
@tonyxrmdavidson thanks, looking here: https://go.dev/dl/
based on the error messages,
I suspect it shall actually specify `.0`, as in `1.21.0`

try that maybe? wdyt?

**Comment by tarilabs** [comment]
(going forward, we should actually revert using bin toolchain and GOBIN, per other tracker)

**Comment by tonyxrmdavidson** [comment]
> @tonyxrmdavidson thanks, looking here: https://go.dev/dl/ based on the error messages, I suspect it shall actually specify `.0`, as in `1.21.0`
> 
> try that maybe? wdyt?

should that be 1.21.9 and not 1.21.0?

**Comment by tarilabs** [comment]
I'm okay with any microversion 👍

**Review by tarilabs — APPROVED** [review]
/lgtm

thanks @tonyxrmdavidson 

/approve

**Pull request merged**
