### PR TITLE
Fix metadata OpenAPI spec

### PR DESCRIPTION
**Pull request by lampajr**
## Description

This PR aims to improve the openapi spec for `MetadataValue` by properly using the `discriminator`.

## How Has This Been Tested?

Checking the generated models and server are correctly bootstrapped
```
make FORCE_SERVER_GENERATION=true clean build
```

Then by running both `unit` and  `robot` tests:

```bash
make test
```

and
```bash
# Start MLMD server
...

# Start model registry
make proxy

# In another terminal
robot test/robot/ && TEST_MODE=python robot test/robot/MRandLogicalModel.robot
```

## Merge criteria:

- [ ] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by tarilabs** [comment]
TBD:
- [ ] generation of `internal/server/openapi/type_asserts.go` still need some fixing
- [ ] clarify if we really need to bump "version" to v1alpha2

**Comment by dhirajsb** [comment]
Given it's a breaking change in the API, we have to bump api version. 
The discriminator change lgtm.

**Comment by lampajr** [comment]
> TBD:
> 
> * [ ]  generation of `internal/server/openapi/type_asserts.go` still need some fixing
> * [ ]  clarify if we really need to bump "version" to v1alpha2

Addressed both items:
* Updated the `type_asserts` patch to fix the autogenerated code
* Bumped openapi spec version to `v1alpha2`

**Comment by lampajr** [comment]
If the change looks good, I would suggest to merge with `squash`!

**Pull request merged**
