### PR TITLE
Adds support for PATCH requests in live cluster mode

### PR DESCRIPTION
**Pull request by alexcreasy**
## Description

Adds support for PATCH requests when mock mode is disabled.

### Test Environment Setup
  * Deploy MR to kind
  * Run BFF locally with MR API mock mode disabled, e.g. `make run PORT=4000 MOCK_K8S_CLIENT=true MOCK_MR_CLIENT=false`
  * Create a RegisteredModel to work with: 
```
curl -i -X POST "http://localhost:4000/api/v1/model_registry/model-registry/registered_models" \
     -H "Content-Type: application/json" \
     -d '{ "data": {
  "customProperties": {
    "my-label9": {
      "metadataType": "MetadataStringValue",
      "string_value": "val"
    }
  },
  "description": "Old description",
  "externalId": "9927",
  "name": "bella",
  "owner": "eder",
  "state": "LIVE"
}}'
```
  * Create a ModelVersion to work with: 
 ```
curl -i -X POST "http://localhost:4000/api/v1/model_registry/model-registry/registered_models/1/versions" \
     -H "Content-Type: application/json" \
     -d '{ "data": {
  "customProperties": {
    "my-label9": {
      "metadataType": "MetadataStringValue",
      "string_value": "val"
    }
  },
  "description": "Old description",
  "externalId": "9928",
  "name": "ModelVersion One",
  "state": "LIVE",
  "author": "alex",
  "registeredModelId": "1"
}}'
```
### Test method
*NOTE: when performing the PATCH steps, you may need to change the IDs at the end of the path, based on the IDs returned when you created the models in the environment setup stages*
1. Perform a PATCH on the RegisteredModel:
```
curl -i -X PATCH "http://localhost:4000/api/v1/model_registry/model-registry/registered_models/1" \
-H "Content-Type: application/json" \
-d '{ "data": {
  "description": "New description"
}}'
```
2. Verify you get a 200 response and the returned body contains the updated description.
3. Perform a PATCH on the ModelVersion:
```
curl -i -X PATCH "http://localhost:4000/api/v1/model_registry/model-registry/model_versions/1" \
     -H "Content-Type: application/json" \
-d '{ "data": {
  "description": "New description"
}}'
```
4. Verify you get a 200 response and the returned body contains the updated description.
## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [x] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work.
- [x] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]
/lgtm

Tested the endpoints, both work great

**Review by ederign — APPROVED** [review]

**Pull request merged**
