### PR TITLE
core: make server generation use default factories

### PR DESCRIPTION
**Pull request by tarilabs**
alternative of https://github.com/kubeflow/model-registry/pull/527

## Description
- 0cce633466311c34eef19661222f414de1cca9d5 show required changes in openapi codegeneration to align model
- 543cea11c3ccbfa77d454f42d718b5156e4c9596 codegeneration
- 3701535248fc4088328bfcd508b664783e02b0bf non regression testing in Python, using client to prepare the data, and UI code describing the issue

## How Has This Been Tested?
Locally with Go test, and `poetry run pytest --e2e -s -k test_patch_mm` after `make test-e2e`.

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [x] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work.
- [x] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

### CODE REVIEW

**Review by isinyaaa — APPROVED** [review]
the workaround is fine by me :)

**Comment by Al-Pragliola** [comment]
more than an alternative I think this PR is complementary to the work done in https://github.com/kubeflow/model-registry/pull/527 , @isinyaaa @tarilabs wdyt? It would be nice to merge both of them as artifactType should be indeed optional in the openapi contract

**Comment by tarilabs** [comment]
sounds awesome, feel free to add on top of this branch? So we make sure it's covered by the testing too

**Comment by tarilabs** [comment]
superseeded by https://github.com/kubeflow/model-registry/pull/538

**Pull request closed without merging**
