### PR TITLE
Moving all non-public packages to internal

### PR DESCRIPTION
**Pull request by ederign**
Moving all non-public packages to internal

## Description
The goal of this PR is to move all non-public packages to internal

## How Has This Been Tested?
Run the BFF, Run the FE, built the docker image.

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [X] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work.
- [X] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

### CODE REVIEW

**Review by Griffin-Sullivan — APPROVED** [review]
Works for me. Tests are all passing, running locally does fine, and I even tested the new image inside a kind cluster: 
```
curl http://localhost:4000/api/v1/healthcheck
```
```
{
        "status": "available",
        "system_info": {
                "version": "1.0.0"
        }
}
```
```
curl http://localhost:4000/api/v1/model_registry
```
```
{}
```

**Comment by ederign** [comment]
@tarilabs Alex is on PTO, do you ming to merge this?

**Pull request merged**
