### PR TITLE
Merge model registry codebase from https://github.com/opendatahub-io/model-registry

### PR DESCRIPTION
**Pull request by dhirajsb**
## Description

Merged main branch from opendatahub-io org into kubeflow org model-registry repo.

## How Has This Been Tested?

Verified docker image build locally on the merged branch. 

## Merge criteria:

- [X] The commits and have meaningful messages; 
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by tarilabs** [comment]
The purpose of this PR should be to merge commit, NOT squash.

**Comment by dhirajsb** [comment]
@tarilabs fixed the squash comment in description that came from the PR template.

**Comment by tarilabs** [comment]
Yeah @dhirajsb no troubles with the original PR description; just nothing if anyone work on this PR, we eventually need merge commit, not squash.

**Comment by dhirajsb** [comment]
@andreyvelich is the kubeflow CI going to squash commits automatically once the tests pass? We need to ensure that we do a merge commit.

**Comment by andreyvelich** [comment]
> @andreyvelich is the kubeflow CI going to squash commits automatically once the tests pass? We need to ensure that we do a merge commit.

Yes, I think for merge commit someone with write permission should manually merge the PR selecting the appropriate setting.

@zijianjoy @kubeflow/kubeflow-steering-committee To make this operation do we need that all commit authors sign the CLA?

**Comment by zijianjoy** [comment]
1. All contributors need to sign CLA/DCO. It makes merging very difficult, so my current understanding is: Creating a single new PR is easier for merging.
2. If all contributors have signed CLA, there is an option to merge commit without squashing.

8RfTVWDgoxrPQak

**Review by terrytangyuan — COMMENTED** [review]
I believe all committers come from Red Hat and we've signed corporate CLA so we might be fine.

**Comment by dhirajsb** [comment]
@andreyvelich @zijianjoy all contributors are on the Red Hat corporate CLA and cla check is successful now.

**Comment by zijianjoy** [comment]
Thank you for confirming @dhirajsb , Should I perform which one of the following?

1. `Create a merge commit: All commits from this branch will be added to the base branch via a merge commit`
1. `Rebase and merge: The 235 commits from this branch will be rebased and added to the base branch`

**Comment by dhirajsb** [comment]
Lets merge commit to preserve commit ids if we can. @tarilabs wdyt?

**Comment by dhirajsb** [comment]
I think @tarilabs has the rights to do it as well. Let's wait for his confirmation tomorrow.

**Comment by tarilabs** [comment]
> Lets merge commit to preserve commit ids if we can. @tarilabs wdyt?

yes, https://github.com/kubeflow/model-registry/pull/6#issuecomment-1932970388

> I think @tarilabs has the rights to do it as well. Let's wait for his confirmation tomorrow.

yes, I confirm I have auth now to merge-commit; I'm just holding on "pushing the button" as I want to ensure we're fully coordinated internally (I can't act autonomously there), in order to _minimise_ disruptions for our colleagues.

Thank you for the PR again @dhirajsb this is super helpful

**Comment by dhirajsb** [comment]
@andreyvelich @zijianjoy It looks like the CLA check added a constraint for number of commits >250, which is failing. And there is a new DCO check that's failing since none of the original commits were signed. 
Can we relax these constraints to merge this initial version for model registry and add them back in for the project going forward?

**Comment by terrytangyuan** [comment]
+1 to merge this manually since all the new commits are from Red Hat with a signed corporate CLA.

**Comment by tarilabs** [comment]
+1 to merge this manually given:
- discussions in recent KF community meetings on "uplifting code"
- discussions in recent KF Model Registry meetings on "uplifting code"
- validations in https://github.com/kubeflow/model-registry/pull/6#issuecomment-1939599087 and https://github.com/kubeflow/model-registry/pull/6#issuecomment-1953091983

👉  I will merge-commit to preserve commit hash (https://github.com/kubeflow/model-registry/pull/6#issuecomment-1939776029) and code-attributions, all commits in this PR are coming from (human) Red Hatters or by bots from ODH/model-registry repo work operated by Red Hatters.

I've also checked out the PR locally to ensure LICENSE, OWNERS and README.md are as intended.

Thank you @dhirajsb for the great work and maintaining this PR to requests

**Pull request merged**
