### PR TITLE
gha: provide py dist as gh artifact

### PR DESCRIPTION
**Pull request by tarilabs**
## Description
Hopefully ease out local testing, without having to wait for a release for the py whl.

For more information, reference the [github documentation](https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization#:~:text=By%20default%2C%20the%20artifacts%20and%20log%20files%20generated%20by%20workflows%20are%20retained%20for%2090%20days%20before%20they%20are%20automatically%20deleted.).

## How Has This Been Tested?
n/a

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [x] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [x] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

### CODE REVIEW

**Comment by tarilabs** [comment]
Example available in https://github.com/kubeflow/model-registry/actions/runs/10727157971?pr=352
wdyt @isinyaaa ?

**Review by isinyaaa — APPROVED** [review]
good idea!

**Comment by tarilabs** [comment]
I've evaluated the potential of using an ad-hoc session with [fee9326](https://github.com/kubeflow/model-registry/pull/352/commits/fee93267dedd33e52b51efee581b9496540018ed)
but I'm not very happy with this translating into its own GH runner.

**Comment by tarilabs** [comment]
So I'm binding this to the 
```
matrix.session == 'tests' && matrix.python == '3.12'
```

To avoid defining a new session and GHA runner just for having an archive of the dist

**Review by rareddy — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
