### PR TITLE
Add lucferbux and Griffin-Sullivan as approvers in the UI

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Add @lucferbux and @Griffin-Sullivan as approvers in the UI repo

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [ ] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

### CODE REVIEW

**Comment by lucferbux** [comment]
@tarilabs @ederign I think we have enough contributions to make ourselves as approvers, this will help in our velocity when part of the team is out.

**Comment by tarilabs** [comment]
this adds in `clients/ui` scope which

/lgtm

I leave to @ederign for approval, thanks!

**Comment by tarilabs** [comment]
update. please make sure you are a KF member first. Once that it's done, we can merge this

**Comment by ederign** [comment]
Proposal for membership for @lucferbux https://github.com/kubeflow/internal-acls/pull/726

**Comment by ederign** [comment]
Proposal for membership for @Griffin-Sullivan https://github.com/kubeflow/internal-acls/pull/728

**Review by ederign — APPROVED** [review]

**Pull request merged**
