### PR TITLE
Add golangci-lint timeout to fix CI

### PR DESCRIPTION
**Pull request by Griffin-Sullivan**
## Description
Adding a golangci-lint config file to increase our timeout, so we won't get failures in CI. Setting the timeout to 3m (default is 1m). Open to discussion if 3m is too big or too small.

## How Has This Been Tested?
Changed timeout to something really short (1ms) and got:
```
ERRO Timeout exceeded: try increasing it by passing --timeout option 
```

## Merge criteria:

- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [x] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work.
- [x] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

If you have UI changes

- [ ] The developer has added tests or explained why testing cannot be added.
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Verify that UI/UX changes conform the UX guidelines for Kubeflow.

### CODE REVIEW

**Comment by tarilabs** [comment]
another example: https://github.com/kubeflow/model-registry/actions/runs/11552360466/job/32151269012

**Comment by tarilabs** [comment]
another example: https://github.com/opendatahub-io/model-registry/actions/runs/11552616877/job/32152065731?pr=141

**Comment by ederign** [comment]
Thanks for this, Griffin; let's try with 3 minutes. if it's not enough we can revisit this later.

**Review by ederign — APPROVED** [review]

**Pull request merged**
