### PR TITLE
build(deps): bump github.com/kubeflow/model-registry from 0.2.4-alpha to 0.2.5-alpha in /clients/ui/bff

### PR DESCRIPTION
**Pull request by ederign**
Fixes https://github.com/kubeflow/model-registry/pull/330
## Merge criteria:

- [X] All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)

- [X] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work.
- [X] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).

### CODE REVIEW

**Comment by ederign** [comment]
@tarilabs I'm the one who created this PR! Maybe assign to @alexcreasy ?

**Comment by tarilabs** [comment]
> @tarilabs I'm the one who created this PR! Maybe assign to @alexcreasy ?

whoops :) 

/assign @alexcreasy

**Review by tarilabs — APPROVED** [review]
/lgtm

@ederign , thank you

/approve

**Pull request merged**
